---
title: "Data manipulation"
author: 'Stefano Longo, UNI: sl4444'
date: "08/10/2019"
output: html_document
---

```{r, warning=F, message=F}
load('../data/Restaurant_Inspections.RData')
library(dplyr)
library(lubridate)
```

```{r}
top.ten.cuisines <- top_n(data.frame(table(res$CUISINE.DESCRIPTION)), 10, Freq) #find top ten cuisines by frequency

df <- res %>%
  mutate(DATE = as.POSIXct(strptime(as.character(res$INSPECTION.DATE), "%m/%d/%Y"))) %>% #make date variable
  filter(CUISINE.DESCRIPTION %in% top.ten.cuisines$Var1 & DATE >= "2016-01-01") %>% # Filter relevant cuisines and disregards old dates 2015
  plyr::arrange(DATE) %>% 
  mutate(MONTH = month(DATE),           #Extract month 
         
         YEAR = substr(year(DATE),3,4), #Extract year
         
         Q = case_when(                 #Extract quarter
           MONTH %in% c(1:3) ~ "Q1",
           MONTH %in% c(4:6) ~ "Q2",
           MONTH %in% c(7:9) ~ "Q3",
           MONTH %in% c(9:12) ~ "Q4"),
         
         QUARTER = paste(Q, YEAR, sep="-"),   #Create quarter variable and order it
         QUARTER = factor(QUARTER, levels = c("Q1-16", "Q2-16", "Q3-16", "Q4-16",
                                              "Q1-17", "Q2-17", "Q3-17", "Q4-17",
                                              "Q1-18", "Q2-18", "Q3-18", "Q4-18",
                                              "Q1-19", "Q2-19", "Q3-19", "Q4-19")),
    
    NEIGHBOURHOOD = case_when( #Create Neighborhood variable
      ZIPCODE %in% c(10453, 10457, 10460) ~ "Central Bronx",
      ZIPCODE %in% c(10458, 10467, 10468) ~ "Bronx Park and Fordham",
      ZIPCODE %in% c(10451, 10452, 10456) ~ "High Bridge and Morrisania",
      ZIPCODE %in% c(10454, 10455, 10459, 10474) ~ "Hunts Point and Mott Haven",
      ZIPCODE %in% c(10463, 10471) ~ "Kingsbridge and Riverdale",
      ZIPCODE %in% c(10466, 10469, 10470, 104750) ~ "Northeast Bronx",
      ZIPCODE %in% c(10461, 10462,10464, 10465, 10472, 10473) ~ "Southeast Bronx",
      
      ZIPCODE %in% c(11212, 11213, 11216, 11233, 11238) ~ "Central Brooklyn	",
      ZIPCODE %in% c(11209, 11214, 11228) ~ "Southwest Brooklyn",
      ZIPCODE %in% c(11204, 11218, 11219, 11230) ~ "Borough Park",
      ZIPCODE %in% c(11234, 11236, 11239) ~ "Canarsie and Flatlands",
      ZIPCODE %in% c(11223, 11224, 11229, 11235) ~ "Southern Brooklyn",
      ZIPCODE %in% c(11201, 11205, 11215, 11217, 11231) ~ "Northwest Brooklyn",
      ZIPCODE %in% c(11203, 11210, 11225, 11226) ~ "Flatbush",
      ZIPCODE %in% c(11207, 11208) ~ "East New York and New Lots",
      ZIPCODE %in% c(11211, 11222) ~ "Greenpoint",
      ZIPCODE %in% c(11220, 11232) ~ "Sunset Park",
      ZIPCODE %in% c(11206, 11221, 11237) ~ "Bushwick and Williamsburg",
    
      ZIPCODE %in% c(10026, 10027, 10030, 10037, 10039) ~ "Central Harlem",
      ZIPCODE %in% c(10001, 10011, 10018, 10019, 10020, 10036) ~ "Chelsea and Clinton",
      ZIPCODE %in% c(10029, 10035) ~ "East Harlem",
      ZIPCODE %in% c(10010, 10016, 10017, 10022) ~ "Gramercy Park and Murray Hill",
      ZIPCODE %in% c(10012, 10013, 10014) ~ "Greenwich Village and Soho",
      ZIPCODE %in% c(10004, 10005, 10006, 10007, 10038, 10280) ~ "Lower Manhattan	",
      ZIPCODE %in% c(10002, 10003, 10009) ~ "Lower East Side",
      ZIPCODE %in% c(10021, 10028, 10044, 10065, 10075, 10128) ~ "Upper East Side",
      ZIPCODE %in% c(10023, 10024, 10025) ~ "Upper West Side",
      ZIPCODE %in% c(10031, 10032, 10033, 10034, 10040) ~ "Inwood and Washington Heights",
      
      ZIPCODE %in% c(11361, 11362, 11363, 11364) ~ "Northeast Queens",
      ZIPCODE %in% c(11354, 11355, 11356, 11357, 11358, 11359, 11360) ~ "North Queens",
      ZIPCODE %in% c(11365, 11366, 11367) ~ "Central Queens",
      ZIPCODE %in% c(11412, 11423, 11432, 11433, 11434, 11435, 11436) ~ "Jamaica",
      ZIPCODE %in% c(11101, 11102, 11103, 11104, 11105, 11106) ~ "Northwest Queens",
      ZIPCODE %in% c(11101, 11102, 11103, 11104, 11105, 11106) ~ "West Central Queens",
      ZIPCODE %in% c(11691, 11692, 11693, 11694, 11695, 11697) ~ "Rockaways",
      ZIPCODE %in% c(11004, 11005, 11411, 11413, 11422, 11426, 11427, 11428, 11429) ~ "Southeast Queens",
      ZIPCODE %in% c(11414, 11415, 11416, 11417, 11418, 11419, 11420, 11421) ~ "Southwest Queens",
      ZIPCODE %in% c(11368, 11369, 11370, 11372, 11373, 11377, 11378) ~ "West Queens",
      
      ZIPCODE %in% c(10302, 10303, 10310) ~ "	Port Richmond",
      ZIPCODE %in% c(10306, 10307, 10308, 10309, 10312) ~ "South Shore",
      ZIPCODE %in% c(10301, 10304, 10305) ~ "Stapleton and St. George",
      ZIPCODE %in% c(10314) ~ "Mid-Island"))
```



```{r}
#Create year data for first graph

dt1 = na.omit(res, cols = ZIPCODE)
dt1  = dt1[dt1$INSPECTION.DATE != 01/01/1900,]
dt1 = dt1[dt1$GRADE %in% c("A","B","C"),]
df_result <- matrix(NA,nrow=2000,ncol=6)

colnames(df_result) = c("ZIPCODE","YEAR","A","B","C","AVERAGE_SCORE")
var1 = as.character(unlist(lapply(unique(dt1$ZIPCODE),function(x) rep(x,5))))
df_result = cbind(var1,rep(c(2015,2016,2017,2018,2019),length(var1)/5))

grades = data.frame(matrix(nrow = length(var1),ncol = 3))

for(i in 1:length(var1)){
  grades[i,1] = nrow(dt1[(dt1$ZIPCODE ==
                      df_result[i,1])&(substring(dt1$INSPECTION.DATE,7,10)==df_result[i,2])&(dt1$GRADE =="A"),])
  grades[i,2] = nrow(dt1[(dt1$ZIPCODE ==
                            df_result[i,1])&(substring(dt1$INSPECTION.DATE,7,10)==df_result[i,2])&(dt1$GRADE =="B"),])
  grades[i,3] = nrow(dt1[(dt1$ZIPCODE ==
                            df_result[i,1])&(substring(dt1$INSPECTION.DATE,7,10)==df_result[i,2])&(dt1$GRADE =="C"),])
}

score = apply(df_result, 1 ,function(x) mean(dt1[(dt1$ZIPCODE == x[1])&(substring(dt1$INSPECTION.DATE,7,10)==x[2]),]$SCORE))

df_result = cbind(df_result,grades,score)

colnames(df_result) = c("zipcode","year","A","B","C","average_score")

df_result_omit<-na.omit(df_result)

save(df_result_omit, file="../output/score_dist.RData")
```

```{r}
# Pre-processing for insp_freq.csv
insp_date <- as.character(res$INSPECTION.DATE)
month_freq <- c(type = "character")
year_freq <- c(type = "character")
colnames(insp_freq) <-c("Month", "Year")
for(i in 1:393129){
  month_freq[i] <- substr(insp_date[i], 1,2)
  #insp_freq[i,2] <- substr(insp_date[i], 7,10)
}
mon_str <- function(s){
  return(substr(s,1,2))
}
month_freq <- aaply(insp_date,1,mon_str)
year_str <- function(s){
  return(substr(s,7,10))
}
year_freq <- aaply(insp_date,1,year_str)
insp_freq <- data.frame("Month" = month_freq, "Year" = year_freq)
#write.csv(insp_freq,file="insp_freq.csv",quote=F,row.names = F)

```
```{r}
#Create quarterly data for second graph
quarter.scores <- df %>%
  select(CUISINE.DESCRIPTION, SCORE, QUARTER, YEAR) %>%
  group_by(CUISINE.DESCRIPTION, QUARTER) %>%
  summarise(AVG_SCORE = round(mean(SCORE, na.rm = T),1))

save(quarter.scores, file="../output/Quarter_scores.RData")
```





